remote_theme:       StartBootstrap/startbootstrap-clean-blog-jekyll
title:              Dog Foot
email:              xoiitto2@gmail.com
description:        xoiitto 기술 블로그
author:             Start Bootstrap
baseurl:            "/xoiitto.github.io"
url:                "https://xoiitto.github.io"

# Social Profiles
twitter_username:   xoiitto
github_username:    xoiitto
facebook_username:  xoiitto
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
